### ZSH CONFIG

export ZSH=/Users/douglas/.oh-my-zsh
export UPDATE_ZSH_DAYS=8

ZSH_THEME="muse"
HIST_STAMPS="yyyy-mm-dd"

JIRA_RAPID_BOARD="true"

plugins=(
  aws
  docker
  docker-compose
  gitfast
  jira
  kubectl
  osx
  pip
  python
  rand-quote
  yarn
)

source $ZSH/oh-my-zsh.sh


### GENERAL

export HISTFILE=~/.zsh_history
export HISTSIZE=50000000
export HISTCONTROL=ignoredups

export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/opt/python/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin

# enable iterm integration
source ~/.iterm2_shell_integration.zsh

# dylan's tunnel helper function
function tunnel {
   ssh -f $1 -L $2:localhost:$3 -N
}


### HOMEBREW

# fix brew installed ctags
alias ctags="`brew --prefix`/bin/ctags"

# git defaults to vi which will use built in vim instead of brew one
export GIT_EDITOR=vim

# fzf setup and config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# remap file find binding
bindkey -r '^T'
bindkey '^F' fzf-file-widget

# no-height means ALWAYS use fullscreen, including for built in keybindings
export FZF_DEFAULT_OPTS="--reverse --no-mouse --no-height --preview 'head -50 {}'"


### PYTHON

export PYLINTRC=/Users/douglas/.pylintrc

# remove all pyc files in current dir
alias killpyc="find . -name '*.pyc' -delete"

# virtualenvwrapper-like helper functions
mkdir -p /Users/douglas/.virtualenvs

function mkvirtualenv {
  if [[ $1 = "" ]]; then
    echo "Please specify a name for your environment";
  else
    python -m venv /Users/douglas/.virtualenvs/$1;
    source /Users/douglas/.virtualenvs/$1/bin/activate;
  fi
}

function rmvirtualenv {
  rm -r /Users/douglas/.virtualenvs/$1
}

function workon {
  if [[ $1 = "" ]]; then
    ls -1 /Users/douglas/.virtualenvs/;
  else
    source /Users/douglas/.virtualenvs/$1/bin/activate;
  fi
}


### JAVASCRIPT

export REACT_EDITOR=mvim

# react-native development stuff
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator
export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-12.jdk/Contents/Home"
